- name: install openstack CLI tools
  pip:
    name: '{{item}}'
    state: present
    extra_args: '--user'
  with_items:
    - python-openstackclient
    - python-designateclient
    - python-neutronclient
