- name: create docker config dir
  file:
    path: '{{ansible_user_dir}}/.docker'
    state: directory

- name: write docker daemon config
  template:
    src: docker/daemon.j2
    dest: '{{ansible_user_dir}}/.docker/daemon.json'

- name: Check if Homebrew is already installed
  stat:
    path: /usr/local/bin/brew
  register: brew

  # credit http://rapidprogrammer.com/how-to-install-homebrew-with-ansible
- name: Install Homebrew
  shell: |
    yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not brew.stat.exists

- homebrew_cask:
    name: '{{item.key}}'
    install_options: '{{item.value.options|default(omit)}}'
  with_dict: '{{homebrew_casks}}'
  tags: [homebrew]

- homebrew_tap:
    name: '{{item.key}}'
  with_dict: '{{homebrew_taps}}'
  tags: [homebrew]

- homebrew:
    name: '{{item.key}}'
    install_options: '{{item.value.options|default(omit)}}'
  with_dict: '{{homebrew_packages}}'
  tags: [homebrew]
