- yum: 
    name: '{{item}}'
    state: present
  with_items:
    - epel-release

- yum: 
    name: '{{item}}'
    state: present
  with_items:
    - bash-completion-extras
    - python-pip
    - python-devel
    - unzip
    - bind-utils
    - nmap
    - net-tools
    - pciutils
    - lshw
    - dmidecode
    - tcpdump
    - traceroute
    - iperf3
    - sysstat

- yum:
    name: '{{item.key}}'
    state: present
  with_dict: '{{dnf_packages}}'

- import_tasks: '_os-linux.yml'
