- yum: 
    name: '{{item}}'
    state: present
  with_items:
    - epel-release
    - python-pip
    - python-devel
    - unzip

- yum: 
    name: '{{item}}'
    state: present
  with_items:
    - bash-completion-extras

- yum:
    name: '{{item.key}}'
    state: present
  with_dict: '{{dnf_packages}}'

- import_tasks: '_os-linux.yml'
