- name: create directories under $HOME
  file:
    name: '{{ansible_env["HOME"]}}/{{item}}'
    state: directory
  with_items:
    - .bashrc.d
    - .bash_completion.d
    - bin

- name: write bashrc.d scriptlets
  template:
    src: '{{item}}'
    dest: '{{ansible_env["HOME"]}}/.bashrc.d/{{item|basename|regex_replace("\.j2$","")}}'
  with_fileglob:
    - 'templates/bashrc.d/*.j2'

- name: create ~/.bashrc
  copy:
    content: |
      for f in ~/.bashrc.d/*; do
        . $f
      done
    dest: '{{ansible_env["HOME"]}}/.bashrc'

- name: create ~/.bash_profile
  copy:
    content: |
      . ~/.bashrc
    dest: '{{ansible_env["HOME"]}}/.bash_profile'
