- name: create directories under $HOME
  file:
    name: '{{ansible_env["HOME"]}}/{{item}}'
    state: directory
  with_items:
    - .bash_profile.d
    - .bash_completion.d
    - bin

- name: write bash_profile.d scriptlets
  template:
    src: '{{item}}'
    dest: '{{ansible_env["HOME"]}}/.bash_profile.d/{{item|basename|regex_replace("\.j2$","")}}'
  with_fileglob:
    - 'templates/bash_profile.d/*.j2'

- name: create ~/.bash_profile
  copy:
    content: |
      for f in ~/.bash_profile.d/*; do
        . $f
      done
    dest: '{{ansible_env["HOME"]}}/.bash_profile'
