- name: create directories under $HOME
  file:
    name: '{{ansible_env["HOME"]}}/{{item}}'
    state: directory
  with_items:
    - .bash_profile.d
    - .bash_completion.d
    - bin

- name: write bash_profile.d scriptlets
  template:
    src: '{{item}}'
    dest: '{{ansible_env["HOME"]}}/.bash_profile.d/{{item|basename|regex_replace("\.j2$","")}}'
  with_fileglob:
    - 'templates/bash_profile.d/*.j2'

- name: create ~/.bash_profile
  copy:
    content: |
      for f in ~/.bash_profile.d/*; do
        . $f
      done

      test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
    dest: '{{ansible_env["HOME"]}}/.bash_profile'

- import_tasks: _python.yml
  tags: [python]

- import_tasks: _homebrew.yml
  when: ansible_os_family == 'Darwin'
  tags: [homebrew,brew]

- import_tasks: _git.yml
  tags: [git]

- import_tasks: _openstack.yml
  tags: [openstack]
