- import_tasks: _shell.yml
  tags: [shell]

- import_tasks: _python.yml
  tags: [python]

- import_tasks: _homebrew.yml
  when: ansible_os_family == 'Darwin'
  tags: [homebrew,brew]

- import_tasks: _git.yml
  tags: [git]

- import_tasks: _openstack.yml
  tags: [openstack]

- import_tasks: _dotfiles.yml
  tags: [dotfiles]
