- include_tasks: '{{file}}'
  with_items:
  - '_os-{{ansible_distribution|lower}}.yml'
  loop_control:
    loop_var: file
  tags: [distro]

- import_tasks: _shell.yml
  tags: [shell]

- import_tasks: _python.yml
  tags: [python]

- import_tasks: _ruby.yml
  tags: [ruby]

- import_tasks: _git-hg.yml
  tags: [git, hg]

- import_tasks: _openstack.yml
  tags: [openstack]

- import_tasks: _dotfiles.yml
  tags: [dotfiles]

- import_tasks: _hashi.yml
  tags: [hashi]

- import_tasks: _docker.yml
  tags: [docker]
