vagrant_default_provider: vmware_fusion
shell_ps1: '\n`date "+%a%d/%m %H:%M:%S"` \[\033[32m\]\u@\h \[\033[33m\]`pwd`\033[0m\]\n$ '

pip_conf:
  list:
    format: legacy

dotfiles:
  - cookiecutterrc
  - vimrc
  - tmux.conf

cookiecutters:
  tf: https://github.com/boyvinall/tf-cutter.git
  ansible: https://github.com/boyvinall/ansible-cutter.git
  ansible-role: https://github.com/boyvinall/ansible-role-cutter.git

gems:
  json:

dnf_packages:
  ansible:
  bash-completion:
  gnupg:
  golang:
  graphviz:
  jq:
  ImageMagick:
  mercurial:
  patch:
  ruby-devel:
  rubygems:

linux_pip:
  cookiecutter:
  httpie:

common_pip:
  yq:

homebrew_casks:
  osxfuse:

homebrew_packages:
  ansible:
  bash:
  bash-completion:
  cmake:
  consul-template:
  cookiecutter:
  coreutils:
  curl:
  delve:
  gawk:
  git:
  git-lfs:
  go:
  graphviz:
  gnu-sed:
    options: with-default-names
  gnu-tar:
  httpie:
  jq:
  imagemagick:
  mercurial:
  moreutils:
  mtr:
  mysql:
  nmap:
  openssl:
  pstree:
  python:
  rclone:
  remake:
  ruby:
  s3cmd:
  shellcheck:
  sqlite:
  ssh-copy-id:
  sshfs:
  terraform:
  tmux:
  vault:
  watch:
  wget:
  wireshark:
    options: with-qt
  youtube-dl:

hashicorp_releases:
  terraform: 0.11.0
  vault: 0.9.0
  consul-template: 0.19.4

# This would be better as a nested dict but that's harder to do with ini_file. To be improved....
gitconfig:
  - { section: push,      option: default,      value: current }
  - { section: core,      option: excludesfile, value: '{{ansible_env["HOME"]}}/.gitignore_global' }
  - { section: gitreview, option: remote,       value: origin }

hgrc:
  - { section: extensions, option: largefiles }
  - { section: extensions, option: graphlog   }
  - { section: extensions, option: eol        }
  - { section: extensions, option: rebase     }
  - { section: extensions, option: transplant }
  - { section: extensions, option: progress   }
  - { section: extensions, option: purge      }
  - { section: extensions, option: strip      }

gitalias:
  st: status
  ci: commit
  di: 'diff --color-words'
  out: '!git fetch && git log FETCH_HEAD..'
  in: '!git fetch && git log ..FETCH_HEAD'
  glog: "log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n'' %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"

