#!/bin/bash
#
#  This is a git command to show status for a tree.
#  Put it in your path and invoke as:
#
#    git stt

quiet=
depth=2

SHORT_OPTS="qd:"
# The OSX getopt command doesn't support long options
while getopts $SHORT_OPTS optchar; do
case "${optchar}" in

  q)
    quiet="true"
    ;;

  d)
    depth=$OPTARG
    ;;

esac
done
  
for f in $(find . -maxdepth $depth -name .git); do 
  D=$(dirname $f)
  pushd $D >/dev/null
  if [ -n "$quiet" ]; then
    git status --porcelain | gawk -v d=$D '
BEGIN {
  modified = added = deleted = unknown = 0
}

/^.M/ { 
  modified++ 
}; 

/^A/ {
  added++
};

/^ D/ {
  deleted++
};

/^\?\? / { 
  unknown++ 
}; 

END { 
  printf("%s%s%s%s  %s\n", 
    (added>0)?"A":" ",
    (deleted>0)?"D":" ",
    (modified>0)?"M":" ", 
    (unknown>0)?"U":" ", 
    d)
}
'
  else
    echo "[$D]"
    git st
  fi
  popd >/dev/null
done
