#!/bin/sh

if [ $# -ne 3 ]; then
    echo "Usage:   git author-rewrite <old_email> <correct_name> <correct_email>"
    exit 2
fi

export OLD_EMAIL="$1"
export CORRECT_NAME="$2"
export CORRECT_EMAIL="$3"

git filter-branch --env-filter '
if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags
